Repository oddpawsx/walltaker-go-client, pull requests merged in 2022-02, with the labels that each got.

#2 update oldWallpaperUrl value
  walltaker.go
Labels: bug

#5 add logic to free up the wallpaper file for macOS users
  walltaker.go
Labels: bug

#6 add go sum file and update go mod
  go.mod
  go.sum
Labels: enhancement

#7 Release/v1.0.2
  go.mod
  go.sum
  walltaker.go
Labels: bug, enhancement

#10 #9 add rich presence
  go.mod
  go.sum
  walltaker.go
  walltaker.toml
Labels: enhancement

#11 Release/v1.1.0
  go.mod
  go.sum
  walltaker.go
  walltaker.toml
Labels: enhancement

#8 implement basic sigkill handling
  walltaker.go
Labels: enhancement

#13 Fix Windows wallpaper caching, not updating
  walltaker.go
Labels: bug

#19 Add CONTRIBUTING.md guide
  CONTRIBUTING.md
Labels: documentation

#21 Update and prettify the toml to use new web URL, closes #20
  walltaker.toml
Labels: enhancement

#22 Feature/17 saved wallpaper naming convention update
  .gitignore
  go.mod
  walltaker.go
Labels: enhancement
